apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
  namespace: lasample
  labels:
    app: hello2
spec:
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: hello2
        image: linuxacademycontent/gitops:hellov1.2
